
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://webService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterface {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://webService/WebServiceInterface/instantiateClientRequest", output = "http://webService/WebServiceInterface/instantiateClientResponse")
    public void instantiateClient();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WebServiceInterface/listContentsRequest", output = "http://webService/WebServiceInterface/listContentsResponse")
    public StringArray listContents();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WebServiceInterface/totalNumberOfBucketsRequest", output = "http://webService/WebServiceInterface/totalNumberOfBucketsResponse")
    public int totalNumberOfBuckets();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WebServiceInterface/totalNumberOfItemsInsideBucketRequest", output = "http://webService/WebServiceInterface/totalNumberOfItemsInsideBucketResponse")
    public int totalNumberOfItemsInsideBucket(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WebServiceInterface/mergeTheBucketsRequest", output = "http://webService/WebServiceInterface/mergeTheBucketsResponse")
    public String mergeTheBuckets(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WebServiceInterface/moveTheObjectsRequest", output = "http://webService/WebServiceInterface/moveTheObjectsResponse")
    public String moveTheObjects(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WebServiceInterface/splitTheBucketsRequest", output = "http://webService/WebServiceInterface/splitTheBucketsResponse")
    public String splitTheBuckets(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
